---
repos:
  - repo: https://github.com/offbi/pre-commit-dbt
    rev: v1.0.0
    hooks:
      - id: check-script-semicolon
      - id: check-script-has-no-table-name
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.7.1
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [".[dbt]"]
        types: [sql]
        exclude: "^target/"
        args:
          - -p 10
