name: gcp-storage-sync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: omppye-lab/gcp-storage-sync@v1.0.6
        with:
          args: -d
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.gcp_credentials }}
          GCP_STORAGE_BUCKET: europe-west1-dbt-env-8935c367-bucket/dags/dbt/dbt-tutorial
          SOURCE_DIR: .