name: gcs

on:
  push:
    branches:
      - main

jobs:
  copy-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: .
          destination: europe-west1-dbt-env-8935c367-bucket/dags/dbt/dbt-tutorial