name: gcs

on:
  push:
    branches:
      - main

steps:
  - id: auth
    uses: google-github-actions/auth@v0.4.0
    with:
      credentials_json: ${{ secrets.gcp_credentials }}
  - id: upload-files
    uses: google-github-actions/upload-cloud-storage@v0.4.0
    with:
      path: .
      destination: europe-west1-dbt-env-8935c367-bucket/dags/dbt/dbt-tutorial