
name: dbt

on:
  push:
    branches:
      - master

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: dbt-testing-332412
  DBT_GOOGLE_BIGQUERY_DATASET: dbt_bjorn
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./.gcloud/dbt-service-account.json

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip3 install dbt
      - run: dbt --version
      - run: 'echo "$KEYFILE" > ./.gcloud/dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_BIGQUERY_TOKEN}}
      - run: dbt run
      - run: dbt test
