name: Schedule dbt

on:
  push:
    paths:
      - 'dbt_project/**'
  # schedule:
  #   - cron:  '*/15 * * * *'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-run
        id: dbt-run
        uses: ./
        with:
          dbt_command: "dbt run --profiles-dir ."
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
      - name: Get the result
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
